/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmojiRouteImport } from './routes/emoji'
import { Route as IndexRouteImport } from './routes/index'

const EmojiRoute = EmojiRouteImport.update({
  id: '/emoji',
  path: '/emoji',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emoji': typeof EmojiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emoji': typeof EmojiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emoji': typeof EmojiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/emoji'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/emoji'
  id: '__root__' | '/' | '/emoji'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmojiRoute: typeof EmojiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/emoji': {
      id: '/emoji'
      path: '/emoji'
      fullPath: '/emoji'
      preLoaderRoute: typeof EmojiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmojiRoute: EmojiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
